### ISSUE TITLE
I was hoping that this component would work in Blazor Web Assembly

### ISSUE THREAD

**Issue by Julianh9** [CodeGator/CG.Blazor.Wizard#3]
I was hoping that this component would work in Blazor Web Assembly

**Comment by martycook** [comment]
Wow. You're right, it should work with WASM. 

There was a reference making everything fail. I fixed that problem - no idea why I was even referencing that to begin with. In any event, it now works with WASM. 

To be sure, I also added a WASM sample application to the project.
